apiVersion: 1
groups:
    - orgId: 1
      name: Phần cứng
      folder: Test
      interval: 1m
      rules:
        - uid: dfct3bliyofswd
          title: ram cao
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: efcpeq0vcvk74c
              model:
                datasource:
                    type: prometheus
                    uid: efcpeq0vcvk74c
                editorMode: code
                expr: 100 * (1 - windows_memory_available_bytes / windows_memory_physical_total_bytes)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 72
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 2m
          annotations:
            description: Dung luong RAM quá 70% trong thoi gian dai
            summary: Ram qua cao 70%
          isPaused: false
          notification_settings:
            receiver: google-chat
