apiVersion: 1
contactPoints:
    - orgId: 1
      name: google-chat
      receivers:
        - uid: efct1ruzuzri8e
          type: webhook
          settings:
            httpMethod: POST
            payload:
                template: "{\n  \"text\": \"\U0001F6A8 {{ .CommonAnnotations.summary }}\\n\\n{{ .CommonAnnotations.description }}\"\n}"
            url: $__env{LINK_CHAT}
          disableResolveMessage: false
