apiVersion: 1
groups:
    - orgId: 1
      name: Phần cứng
      folder: Test
      interval: 1m
      rules:
        - uid: dfct3bliyofswd
          title: Có Server đang sử dụng RAM một cách bất thường
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: efcpeq0vcvk74c
              model:
                datasource:
                    type: prometheus
                    uid: efcpeq0vcvk74c
                editorMode: code
                expr: "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes\r\n      /\r\n      node_memory_MemTotal_bytes\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes\r\n      /\r\n      windows_memory_physical_total_bytes\r\n    )\r\n  )\r\n)\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 2m
          annotations:
            description: 'Ram server {{ $labels.hostname }} : {{ $labels.instance }} vượt 70% trong thời gian dài'
            summary: Ram vượt 80%
          isPaused: false
          notification_settings:
            receiver: google-chat
        - uid: afe73hzhvrdhcc
          title: CPU cao
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: efcpeq0vcvk74c
              model:
                editorMode: code
                expr: "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{mode=\"idle\"}[5m])\r\n))\r\n)\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            description: CPU vượt quá 80% trong thời gian dài
            summary: CPU vượt quá 80%
          isPaused: false
          notification_settings:
            receiver: google-chat
        - uid: afe73oi93q1a8a
          title: Disk sắp full
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: efcpeq0vcvk74c
              model:
                editorMode: code
                expr: "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            description: Ổ cứng đã được sử dụng trên 80%
            summary: Ổ cứng sắp đầy
          isPaused: false
          notification_settings:
            receiver: google-chat
