{
 "title": "CPU server 1",
 "description": "%cpu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes\r\n      /\r\n      node_memory_MemTotal_bytes\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes\r\n      /\r\n      windows_memory_physical_total_bytes\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n100 * (1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\nor\r\n(\r\n100 * (1 - avg by (instance) (\r\n  rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\",mode=\"idle\"}[5m])\r\n))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_memory_MemAvailable_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      node_memory_MemTotal_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n      windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n      /\r\n      windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "targets": [
    {
     "expr": "(\r\n  100 * (\r\n    1 - (\r\n      node_filesystem_avail_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n      /\r\n      node_filesystem_size_bytes{instance=\"192.168.88.219:9182\",fstype!=\"tmpfs\",fstype!=\"overlay\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\nor\r\n(\r\n  100 * (\r\n    1 - (\r\n     windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n      /\r\n      windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\",volume=~\"[A-Z]:\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}