{
 "title": "CPU server 1",
 "description": "%cpu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - avg by(instance) (\r\n    rate(windows_cpu_time_total{mode=\"idle\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_memory_available_bytes\r\n    /\r\n    windows_memory_physical_total_bytes\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_logical_disk_free_bytes{volume!=\"HarddiskVolume1\"}\r\n    /\r\n    windows_logical_disk_size_bytes{volume!=\"HarddiskVolume1\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - avg by (instance) (\r\n    rate(windows_cpu_time_total{instance=\"192.168.88.219:9182\", mode=\"idle\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU SV 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - avg by (instance) (\r\n    rate(windows_cpu_time_total{instance=\"localhost:9182\", mode=\"idle\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Server 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_memory_available_bytes{instance=\"192.168.88.219:9182\"}\r\n    /\r\n    windows_memory_physical_total_bytes{instance=\"192.168.88.219:9182\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM SV 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_memory_available_bytes{instance=\"localhost:9182\"}\r\n    /\r\n    windows_memory_physical_total_bytes{instance=\"localhost:9182\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_logical_disk_free_bytes{instance=\"192.168.88.219:9182\", volume!=\"HarddiskVolume1\"}\r\n    /\r\n    on(instance, volume)\r\n    windows_logical_disk_size_bytes{instance=\"192.168.88.219:9182\", volume!=\"HarddiskVolume1\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK SV2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    windows_logical_disk_free_bytes{instance = \"localhost:9182\", volume!=\"HarddiskVolume1\"}\r\n    /\r\n    windows_logical_disk_size_bytes{instance = \"localhost:9182\", volume!=\"HarddiskVolume1\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}